### PR TITLE
fix: checkVAT for multiple countries with Brazil on the list

### PR DESCRIPTION
**Pull request by andrebazoli**
It fixes the [issue](https://github.com/se-panfilov/jsvat/issues/113) when multiple countries were used to check whether a VAT is valid and Brazil was on the list before the country where the VAT is valid.

The solution is explained in https://github.com/se-panfilov/jsvat/commit/da16338c25fabbba6c0a6d55fd45147196688d61

Also, adds a unit test for multiple countries (Brazil, United Kingdom, and Lithuanian)

### CODE REVIEW

**Comment by wilgert** [comment]
Great job!

**Comment by andrebazoli** [comment]
@wilgert do you have any idea when we'll have a new release? 🤔

**Comment by wilgert** [comment]
Normally @se-panfilov does the releases, hopefully he can create one soon!

**Comment by doobas** [comment]
Still no release? It is a major bug and package is unusable

**Pull request merged**
